version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  storm-nimbus:
    image: storm:2.4
    container_name: storm-nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    ports:
      - "6627:6627"
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
    volumes:
      - ./storm/conf:/apache-storm-2.4.0/conf

  storm-supervisor:
    image: storm:2.4
    container_name: storm-supervisor
    command: storm supervisor
    depends_on:
      - storm-nimbus
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
      - STORM_NIMBUS_SEEDS=storm-nimbus
    volumes:
      - ./storm/conf:/apache-storm-2.4.0/conf

  storm-ui:
    image: storm:2.4
    container_name: storm-ui
    command: storm ui
    depends_on:
      - storm-nimbus
    ports:
      - "8080:8080"
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
      - STORM_NIMBUS_SEEDS=storm-nimbus
    volumes:
      - ./storm/conf:/apache-storm-2.4.0/conf

volumes:
  redis_data:
